### ISSUE TITLE
npy4th for loading npy with dtype other than float32

### ISSUE THREAD

**Issue by zhoubolei** [htwaijry/npy4th#1]
Hi,
It seems that npy4th can only load npy format with dtype as float32. When I tried to load a npy with dtype as float16, it only returns the full name of the file, rather than any array content inside the file. 

Can it be fixed? Thanks.

**Comment by htwaijry** [comment]
Hi there,

To my knowledge, torch doesn't support half-precision floats, so if you would want to load it, you would have to get it converted into float32 anyways.
