### ISSUE TITLE
"unsupported data type" error when loading a .npy file  

### ISSUE THREAD

**Issue by fareeha** [htwaijry/npy4th#11]
I am trying to load a .npy file consisting of a numpy array for strings. I also tried saving the array as a table and loading as a .npz file. But neither work. I am only able to load npy files of numeric dtypes.

The error is:
unsupported data type at /tmp/luarocks_npy4th-1.3-1-5975/npy4th/npy4th.cpp:122

Please let me know if I'm missing something or how I can fix this.

**Comment by htwaijry** [comment]
Unfortunately loading string arrays is unsupported at the moment. The library only loads numeric dtypes.
