### ISSUE TITLE
luarocks pulls 1.3-1 version

### ISSUE THREAD

**Issue by puglial** [htwaijry/npy4th#15]
i had hard time debbugging the -a (append) functionality since i was installing version 1.3-1 instead of the 1.3-3, this happen because, apparently, if you do:
`luarocks install npy4th`
luarocks pulls:
`https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/npy4th-1.3-1.rockspec`
instead of the latest version

**Comment by htwaijry** [comment]
Sorry I forgot to upload it to luarocks, I just did. Thanks for finding that out!
