### ISSUE TITLE
array type unsupported while using npy4th.loadnpy()

### ISSUE THREAD

**Issue by Aditi138** [htwaijry/npy4th#17]
a = [('a','b','c'),('c','d','e')]
b = [('a','b','c'),('c','d','e'),('w',e','r')]
array=[]
array.append(a)
array.append(b)
c= np.array(array)

When I save this as an .npy file and try to load in Torch using npy4th, I get the following issue:
array type unsupported[string "lbles = npy4th.loadnpy('/mnt/c/CodeMixed/CNN/..."]:1: unsupported data type at /mnt/c/CodeMixed/CNN/TorchCNN/npy4th/npy4th.cpp:94

**Comment by htwaijry** [comment]
torch does not have string tensors
