### ISSUE TITLE
Library not loaded: libcnpy.dylib

### ISSUE THREAD

**Issue by mingtongh** [htwaijry/npy4th#6]
Hello, 

I've been trying to install npy4th and can't get around a problem with libcnpy.dylib. Would really appreciate some help!

After installation it says `npy4th 1.3-1 is now built and installed` but when I `require 'npy4th'` in torch it reports the following error:

`...mingtong/torch/install/share/lua/5.1/luarocks/loader.lua:117: error loading module 'libnpy4th' from file '/Users/mingtong/torch/install/lib/lua/5.1/libnpy4th.so':
    dlopen(/Users/mingtong/torch/install/lib/lua/5.1/libnpy4th.so, 6): Library not loaded: libcnpy.dylib
  Referenced from: /Users/mingtong/torch/install/lib/lua/5.1/libnpy4th.so
  Reason: image not found`

Looks like it's a problem with the path of libcnpy.dylib. 
I found there was a line stating its exact path:
`-- Installing: /Users/mingtong/torch/install/lib/libcnpy.dylib`

And I did `otool -L /Users/mingtong/torch/install/lib/lua/5.1/libnpy4th.so`

```
/Users/mingtong/torch/install/lib/lua/5.1/libnpy4th.so:
    libcnpy.dylib (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libTH.dylib (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libluaT.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
```

Following [http://stackoverflow.com/questions/29809069/dyld-library-not-loaded-on-os-x](url) I tried  something like 
`install_name_tool -change libcnpy.dylib /Users/mingtong/torch/install/lib/libcnpy.dylib`
but doesn't seem to work. 

Any suggestions? Thanks a lot!

**Comment by htwaijry** [comment]
Try adding this to your ~/.bash_profile

```
export LD_LIBRARY_PATH=/Users/mingtong/torch/install/lib:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=/Users/mingtong/torch/install/lib:$DYLD_LIBRARY_PATH
```

Don't forget to "source" your updated profile before running torch again.

**Comment by mingtongh** [comment]
I just did the above and `source ~/.bash_profile` but still have the same problem...

This article suggests to either use install_name_tool or go back to the source code and find the linker line. Would this apply to my situation?  Many thanks!
http://osiris.laya.com/coding/dylib_linking.html

**Comment by htwaijry** [comment]
This might work as work around:
Try copying libcnpy.dylib to /Users/mingtong/torch/install/lib/lua/5.1/

I will look at the CMake files later.

**Comment by ruotianluo** [comment]
Has it been fixed. I still have the same problem. And I tried to copy the dylib but it didn't work.

**Comment by htwaijry** [comment]
Hmm, I haven't changed the cmakefiles..
Are you getting the same exact issue? did you double check your paths, LD and DYLD?

**Comment by lebedov** [comment]
This is happening because cmake isn't using rpaths on MacOSX. PR https://github.com/htwaijry/npy4th/pull/10 fixes this by switching to the default policy that uses rpaths when building libcnpy.

**Comment by explorerr** [comment]
I just downloaded the latest version of nyp4th on Mac, but I am having the same error... I followed all the suggestions in this thread: setting LD_LIBRARY_PATH,  DYLD_LIBRARY_PATH  and copy the libcnpy.dylib. Any update on how to resolve this?

**Comment by mz2** [comment]
I'm experiencing the same issue.

**Comment by mz2** [comment]
For me this resolved the issue:

```
install_name_tool -change libcnpy.dylib @rpath/libcnpy.dylib "$HOME/torch/install/lib/lua/5.1/libnpy4th.so"
```

**Comment by explorerr** [comment]
Thanks for sharing. I moved to using hdf5.. Anyway, thanks for sharing...

**Comment by htwaijry** [comment]
Sorry for not catching up on this, I've been busy lately.
I will bundle the code together and hopefully that will resolve the issue.
