### ISSUE TITLE
''luarocks make'' gives "void value not ignored as it ought to be" error, and a possible fix

### ISSUE THREAD

**Issue by jiajunwu** [htwaijry/npy4th#8]
Running ''luarocks make" gave me the error:
"void value not ignored as it ought to be" on all _cnpy::npy_save_ function calls (npy4th.cpp line 151, 157, ...),
though I noticed cnpy/cnpy.h is already returning bool.

This could be due to I installed npy4th v1.2 earlier, and there was a cnpy.h somewhere else in the system as the earlier version might return void.

An easy fix is to hard code the path _include "cnpy/cnpy.h"_ instead of _include <cnpy.h>_ at line 8 of npy4th.cpp . It'd be great to fix this in the repo as it may benefit other people with a similar issue.

**Comment by htwaijry** [comment]
Thanks for finding this out!
It does seem to be an issue with updating from 1.2. I'm not sure why cnpy.h installation is not being updated though.

I think I should figure out how to bundle cnpy in a better way. I'll get a fix in there.

Thanks again!

**Comment by jiajunwu** [comment]
That sounds great. Thanks!
